services:
  - type: web
    name: focusbot
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      npm install
      npm run build
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
